---


- name: Check the required variables are set
  assert:
    that:
      - "ha_cluster_pass is defined"
      - "ha_cluster_pass | trim | length > 0"
      - "subscription_id is defined"
      - "subscription_id | trim | length > 0"
      - "azure_active_directory_id is defined"
      - "azure_active_directory_id | trim | length > 0"
      - "stonith_service_principal_application_id is defined"
      - "stonith_service_principal_application_id | trim | length > 0"
      - "stonith_service_principal_application_password is defined"
      - "stonith_service_principal_application_password | trim | length > 0"

- name: Check the required Clustering scripts are available
  when: ansible_os_family == 'Suse'
  stat:
    path: "{{ item }}"
  with_items:
    - "/usr/sbin/ha-cluster-init"
    - "/usr/sbin/ha-cluster-join"
  register: p
  failed_when: not p.stat.exists
