---

  - name: Ensure replication status is active
    shell: "python {{ path_sys_rep_status }} | grep 'overall system replication status: ACTIVE'"
    register: grep_result
    until: grep_result.rc == 0
    changed_when: False
    retries: 30
    delay: 30
    when: is_clustered_system and ansible_hostname == hana_database.nodes[0].dbname
