---

- name: Check hana system replication variables are set and not empty
  assert:
    that:
      - "hana_group is defined"
      - "hana_group | trim | length == 0"
      - "sid is defined"
      - "sid | trim | length == 0"
      - "instance_number is defined"
      - "instance_number | trim | length == 0"
      - "hana_system_user is defined"
      - "hana_system_user | trim | length == 0"
      - "hana_dir is defined"
      - "hana_dir | trim | length == 0"
      - "sap_dir is defined"
      - "sap_dir | trim | length == 0"
      - "tmp_ssfs_dir is defined"
      - "tmp_ssfs_dir | trim | length == 0"
      - "hana_stop_start_timeout is defined"
      - "hana_stop_start_timeout | trim | length == 0"
      - "hana_stop_start_delay is defined"
      - "hana_stop_start_delay | trim | length == 0"

- name: "Check that HANA directory {{ hana_dir }} exists"
  block:
    - stat:
        path: "{{ hana_dir }}"
      register: p
      tags:
        - skip_ansible_lint

    - fail:
        msg: "{{ hana_dir }} is not a directory"
      when: not (p.stat.isdir is defined and p.stat.isdir)
      tags:
        - skip_ansible_lint

- name: "Check that SAP directory {{ sap_dir }} exists"
  block:
    - stat:
        path: "{{ sap_dir }}"
      register: p
      tags:
        - skip_ansible_lint

    - fail:
        msg: "{{ sap_dir }} does not exist"
      when: not (p.stat.isdir is defined and p.stat.isdir)
      tags:
        - skip_ansible_lint

- name: "Check that HANA IDX SVR file {{ path_idx_svr }} exists"
  block:
    - stat:
        path: "{{ path_idx_svr }}"
      register: p
      tags:
        - skip_ansible_lint

    - fail:
        msg: "HANA IDX SVR file {{ path_idx_svr }} does not exist"
      when: p.stat.exists == False
      tags:
        - skip_ansible_lint

- name: "Check if HANA DB Util {{ path_hdbnsutil }} exists"
  block:
    - stat:
        path: "{{ path_hdbnsutil }}"
      register: p
      tags:
        - skip_ansible_lint

    - fail:
        msg: "{{ path_hdbnsutil }} does not exist"
      when: p.stat.exists == False
      tags:
        - skip_ansible_lint

- name: Check that HANA admin user {{ sid_admin_user }} exists
  shell: "id {{ sid_admin_user }}"
  changed_when: false
  become: true
  tags:
    skip_ansible_lint: true

- name: Check that HANA system user ({{ hana_system_user }}) can access the SYSTEM database
  become_user: "{{ sid_admin_user }}"
  shell: >
    source ~/.bashrc ;
    {{ path_hdbsql }} -i {{ instance_number }} -u {{ hana_system_user }} -p '{{ hana_system_user_password }}'
    -n {{ hana_container_address }} '{{ dummy_cmd }}'
  changed_when: false

- name: Check that HANA system user ({{ hana_system_user }}) can access the tenant database {{ hana_tenant_database_name }}
  become_user: "{{ sid_admin_user }}"
  shell: >
    source ~/.bashrc ;
    {{ path_hdbsql }} -i {{ instance_number }} -u {{ hana_system_user }} -p '{{ hana_system_user_password }}'
    -n {{ hana_tenant_address }} '{{ dummy_cmd }}'
  changed_when: false

- name: Check HANA log mode is set to normal
  become_user: "{{ sid_admin_user }}"
  shell: >
    {{ path_hdbsql }} -n localhost -i {{ instance_number }}
    -u SYSTEM -p {{ hana_system_user_password }}
    "SELECT VALUE FROM M_INIFILE_CONTENTS WHERE FILE_NAME='global.ini' AND LAYER_NAME='DEFAULT' AND SECTION='persistence' AND KEY='log_mode'"
  register: p
  failed_when: p.rc != 0 or ("normal" not in p.stdout)
  changed_when: False
  tags:
    - skip_ansible_lint
