---

- name: Ensure expected base directories are present
  file:
    path: "{{ item }}"
    state: directory
    mode: +r
  with_items:
    - "/usr/sap/downloads"
    - "/usr/sap/install/config"
    - "/tmp/app_template"
    - "/sapmnt/{{ app_sid }}/global"
    - "/sapmnt/{{ app_sid }}/profile"

- name: Ensure exports file exists
  template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644
  notify:
    - reload nfsd

- name: Ensure nfsserver is running
  systemd:
    state: started
    name: nfsserver
