---

- name: mount the shared directories
  mount:
    name: "{{ item.nfs_imports }}"
    src: "{{ item.server_host }}:{{ item.nfs_imports }}"
    state: "mounted"
    fstype: "nfs"
    opts: "rw,hard,rsize=65536,wsize=65536,vers=3,retry=3,tcp,noauto,_netdev"
