---
- name: Ensure tasks run with root privledge
  become: true
  block:
    - include_tasks: configure.yml

    - include_tasks: configure_server.yml
      when: target == "server"

    - include_tasks: configure_client.yml
      when: target == "client"
