---

- import_tasks: configure.yml
  become: true

- import_tasks: configure_server.yml
  become: true
  when: target == "server"

- import_tasks: configure_client.yml
  become: true
  when: target == "client"
